# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0131beta/invoicesrpc/invoices.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v0131beta import lnd_grpc.protos.dev.rpc_pb2 as v0131beta_dot_rpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v0131beta/invoicesrpc/invoices.proto',
  package='invoicesrpc',
  syntax='proto3',
  serialized_options=b'Z1github.com/lightningnetwork/lnd/lnrpc/invoicesrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$v0131beta/invoicesrpc/invoices.proto\x12\x0binvoicesrpc\x1a\x13v0131beta/rpc.proto\"(\n\x10\x43\x61ncelInvoiceMsg\x12\x14\n\x0cpayment_hash\x18\x01 \x01(\x0c\"\x13\n\x11\x43\x61ncelInvoiceResp\"\xe4\x01\n\x15\x41\x64\x64HoldInvoiceRequest\x12\x0c\n\x04memo\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x03\x12\x12\n\nvalue_msat\x18\n \x01(\x03\x12\x18\n\x10\x64\x65scription_hash\x18\x04 \x01(\x0c\x12\x0e\n\x06\x65xpiry\x18\x05 \x01(\x03\x12\x15\n\rfallback_addr\x18\x06 \x01(\t\x12\x13\n\x0b\x63ltv_expiry\x18\x07 \x01(\x04\x12%\n\x0broute_hints\x18\x08 \x03(\x0b\x32\x10.lnrpc.RouteHint\x12\x0f\n\x07private\x18\t \x01(\x08\"-\n\x12\x41\x64\x64HoldInvoiceResp\x12\x17\n\x0fpayment_request\x18\x01 \x01(\t\"$\n\x10SettleInvoiceMsg\x12\x10\n\x08preimage\x18\x01 \x01(\x0c\"\x13\n\x11SettleInvoiceResp\"5\n\x1dSubscribeSingleInvoiceRequest\x12\x0e\n\x06r_hash\x18\x02 \x01(\x0cJ\x04\x08\x01\x10\x02\x32\xd9\x02\n\x08Invoices\x12V\n\x16SubscribeSingleInvoice\x12*.invoicesrpc.SubscribeSingleInvoiceRequest\x1a\x0e.lnrpc.Invoice0\x01\x12N\n\rCancelInvoice\x12\x1d.invoicesrpc.CancelInvoiceMsg\x1a\x1e.invoicesrpc.CancelInvoiceResp\x12U\n\x0e\x41\x64\x64HoldInvoice\x12\".invoicesrpc.AddHoldInvoiceRequest\x1a\x1f.invoicesrpc.AddHoldInvoiceResp\x12N\n\rSettleInvoice\x12\x1d.invoicesrpc.SettleInvoiceMsg\x1a\x1e.invoicesrpc.SettleInvoiceRespB3Z1github.com/lightningnetwork/lnd/lnrpc/invoicesrpcb\x06proto3'
  ,
  dependencies=[v0131beta_dot_rpc__pb2.DESCRIPTOR,])




_CANCELINVOICEMSG = _descriptor.Descriptor(
  name='CancelInvoiceMsg',
  full_name='invoicesrpc.CancelInvoiceMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payment_hash', full_name='invoicesrpc.CancelInvoiceMsg.payment_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=114,
)


_CANCELINVOICERESP = _descriptor.Descriptor(
  name='CancelInvoiceResp',
  full_name='invoicesrpc.CancelInvoiceResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=135,
)


_ADDHOLDINVOICEREQUEST = _descriptor.Descriptor(
  name='AddHoldInvoiceRequest',
  full_name='invoicesrpc.AddHoldInvoiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='memo', full_name='invoicesrpc.AddHoldInvoiceRequest.memo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='invoicesrpc.AddHoldInvoiceRequest.hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='invoicesrpc.AddHoldInvoiceRequest.value', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_msat', full_name='invoicesrpc.AddHoldInvoiceRequest.value_msat', index=3,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description_hash', full_name='invoicesrpc.AddHoldInvoiceRequest.description_hash', index=4,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='invoicesrpc.AddHoldInvoiceRequest.expiry', index=5,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fallback_addr', full_name='invoicesrpc.AddHoldInvoiceRequest.fallback_addr', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cltv_expiry', full_name='invoicesrpc.AddHoldInvoiceRequest.cltv_expiry', index=7,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_hints', full_name='invoicesrpc.AddHoldInvoiceRequest.route_hints', index=8,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='private', full_name='invoicesrpc.AddHoldInvoiceRequest.private', index=9,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=366,
)


_ADDHOLDINVOICERESP = _descriptor.Descriptor(
  name='AddHoldInvoiceResp',
  full_name='invoicesrpc.AddHoldInvoiceResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payment_request', full_name='invoicesrpc.AddHoldInvoiceResp.payment_request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=413,
)


_SETTLEINVOICEMSG = _descriptor.Descriptor(
  name='SettleInvoiceMsg',
  full_name='invoicesrpc.SettleInvoiceMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='preimage', full_name='invoicesrpc.SettleInvoiceMsg.preimage', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=451,
)


_SETTLEINVOICERESP = _descriptor.Descriptor(
  name='SettleInvoiceResp',
  full_name='invoicesrpc.SettleInvoiceResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=472,
)


_SUBSCRIBESINGLEINVOICEREQUEST = _descriptor.Descriptor(
  name='SubscribeSingleInvoiceRequest',
  full_name='invoicesrpc.SubscribeSingleInvoiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='r_hash', full_name='invoicesrpc.SubscribeSingleInvoiceRequest.r_hash', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=527,
)

_ADDHOLDINVOICEREQUEST.fields_by_name['route_hints'].message_type = v0131beta_dot_rpc__pb2._ROUTEHINT
DESCRIPTOR.message_types_by_name['CancelInvoiceMsg'] = _CANCELINVOICEMSG
DESCRIPTOR.message_types_by_name['CancelInvoiceResp'] = _CANCELINVOICERESP
DESCRIPTOR.message_types_by_name['AddHoldInvoiceRequest'] = _ADDHOLDINVOICEREQUEST
DESCRIPTOR.message_types_by_name['AddHoldInvoiceResp'] = _ADDHOLDINVOICERESP
DESCRIPTOR.message_types_by_name['SettleInvoiceMsg'] = _SETTLEINVOICEMSG
DESCRIPTOR.message_types_by_name['SettleInvoiceResp'] = _SETTLEINVOICERESP
DESCRIPTOR.message_types_by_name['SubscribeSingleInvoiceRequest'] = _SUBSCRIBESINGLEINVOICEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CancelInvoiceMsg = _reflection.GeneratedProtocolMessageType('CancelInvoiceMsg', (_message.Message,), {
  'DESCRIPTOR' : _CANCELINVOICEMSG,
  '__module__' : 'v0131beta.invoicesrpc.invoices_pb2'
  # @@protoc_insertion_point(class_scope:invoicesrpc.CancelInvoiceMsg)
  })
_sym_db.RegisterMessage(CancelInvoiceMsg)

CancelInvoiceResp = _reflection.GeneratedProtocolMessageType('CancelInvoiceResp', (_message.Message,), {
  'DESCRIPTOR' : _CANCELINVOICERESP,
  '__module__' : 'v0131beta.invoicesrpc.invoices_pb2'
  # @@protoc_insertion_point(class_scope:invoicesrpc.CancelInvoiceResp)
  })
_sym_db.RegisterMessage(CancelInvoiceResp)

AddHoldInvoiceRequest = _reflection.GeneratedProtocolMessageType('AddHoldInvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDHOLDINVOICEREQUEST,
  '__module__' : 'v0131beta.invoicesrpc.invoices_pb2'
  # @@protoc_insertion_point(class_scope:invoicesrpc.AddHoldInvoiceRequest)
  })
_sym_db.RegisterMessage(AddHoldInvoiceRequest)

AddHoldInvoiceResp = _reflection.GeneratedProtocolMessageType('AddHoldInvoiceResp', (_message.Message,), {
  'DESCRIPTOR' : _ADDHOLDINVOICERESP,
  '__module__' : 'v0131beta.invoicesrpc.invoices_pb2'
  # @@protoc_insertion_point(class_scope:invoicesrpc.AddHoldInvoiceResp)
  })
_sym_db.RegisterMessage(AddHoldInvoiceResp)

SettleInvoiceMsg = _reflection.GeneratedProtocolMessageType('SettleInvoiceMsg', (_message.Message,), {
  'DESCRIPTOR' : _SETTLEINVOICEMSG,
  '__module__' : 'v0131beta.invoicesrpc.invoices_pb2'
  # @@protoc_insertion_point(class_scope:invoicesrpc.SettleInvoiceMsg)
  })
_sym_db.RegisterMessage(SettleInvoiceMsg)

SettleInvoiceResp = _reflection.GeneratedProtocolMessageType('SettleInvoiceResp', (_message.Message,), {
  'DESCRIPTOR' : _SETTLEINVOICERESP,
  '__module__' : 'v0131beta.invoicesrpc.invoices_pb2'
  # @@protoc_insertion_point(class_scope:invoicesrpc.SettleInvoiceResp)
  })
_sym_db.RegisterMessage(SettleInvoiceResp)

SubscribeSingleInvoiceRequest = _reflection.GeneratedProtocolMessageType('SubscribeSingleInvoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBESINGLEINVOICEREQUEST,
  '__module__' : 'v0131beta.invoicesrpc.invoices_pb2'
  # @@protoc_insertion_point(class_scope:invoicesrpc.SubscribeSingleInvoiceRequest)
  })
_sym_db.RegisterMessage(SubscribeSingleInvoiceRequest)


DESCRIPTOR._options = None

_INVOICES = _descriptor.ServiceDescriptor(
  name='Invoices',
  full_name='invoicesrpc.Invoices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=530,
  serialized_end=875,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeSingleInvoice',
    full_name='invoicesrpc.Invoices.SubscribeSingleInvoice',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBESINGLEINVOICEREQUEST,
    output_type=v0131beta_dot_rpc__pb2._INVOICE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CancelInvoice',
    full_name='invoicesrpc.Invoices.CancelInvoice',
    index=1,
    containing_service=None,
    input_type=_CANCELINVOICEMSG,
    output_type=_CANCELINVOICERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddHoldInvoice',
    full_name='invoicesrpc.Invoices.AddHoldInvoice',
    index=2,
    containing_service=None,
    input_type=_ADDHOLDINVOICEREQUEST,
    output_type=_ADDHOLDINVOICERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SettleInvoice',
    full_name='invoicesrpc.Invoices.SettleInvoice',
    index=3,
    containing_service=None,
    input_type=_SETTLEINVOICEMSG,
    output_type=_SETTLEINVOICERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVOICES)

DESCRIPTOR.services_by_name['Invoices'] = _INVOICES

# @@protoc_insertion_point(module_scope)
