# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v0131beta.watchtowerrpc import watchtower_pb2 as v0131beta_dot_watchtowerrpc_dot_watchtower__pb2


class WatchtowerStub(object):
    """Watchtower is a service that grants access to the watchtower server
    functionality of the daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/watchtowerrpc.Watchtower/GetInfo',
                request_serializer=v0131beta_dot_watchtowerrpc_dot_watchtower__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=v0131beta_dot_watchtowerrpc_dot_watchtower__pb2.GetInfoResponse.FromString,
                )


class WatchtowerServicer(object):
    """Watchtower is a service that grants access to the watchtower server
    functionality of the daemon.
    """

    def GetInfo(self, request, context):
        """lncli: tower info
        GetInfo returns general information concerning the companion watchtower
        including its public key and URIs where the server is currently
        listening for clients.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchtowerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=v0131beta_dot_watchtowerrpc_dot_watchtower__pb2.GetInfoRequest.FromString,
                    response_serializer=v0131beta_dot_watchtowerrpc_dot_watchtower__pb2.GetInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'watchtowerrpc.Watchtower', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Watchtower(object):
    """Watchtower is a service that grants access to the watchtower server
    functionality of the daemon.
    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/watchtowerrpc.Watchtower/GetInfo',
            v0131beta_dot_watchtowerrpc_dot_watchtower__pb2.GetInfoRequest.SerializeToString,
            v0131beta_dot_watchtowerrpc_dot_watchtower__pb2.GetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
