from enum import Enum


class NodeStatus(Enum):
    STARTED = 'STARTED'
    CHECKING_DOWNLOAD = 'CHECKING_DOWNLOAD'
    DOWNLOADING_SOFTWARE = 'DOWNLOADING_SOFTWARE'
    SOFTWARE_DOWNLOADED = 'SOFTWARE_DOWNLOADED'
    INSTALLING_SOFTWARE = 'INSTALLING_SOFTWARE'
    SOFTWARE_INSTALLED = 'SOFTWARE_INSTALLED'
    SOFTWARE_READY = 'SOFTWARE_READY'

    LOADING_CONFIGURATION = 'LOADING_CONFIGURATION'
    CHECKING_CONFIGURATION = 'CHECKING_CONFIGURATION'
    CONFIGURATION_READY = 'CONFIGURATION_READY'

    STARTING_PROCESS = 'STARTING_PROCESS'
    PROCESS_STARTED = 'PROCESS_STARTED'

    SYNCING = 'SYNCING'
    SYNCED = 'SYNCED'

    STOPPED = 'STOPPED'


SoftwareStatus = NodeStatus
