from enum import Enum


class NodeStatus(Enum):
    CHECKING_DOWNLOAD = 'CHECKING_DOWNLOAD'
    DOWNLOADING_SOFTWARE = 'DOWNLOADING_SOFTWARE'
    SOFTWARE_DOWNLOADED = 'SOFTWARE_DOWNLOADED'
    INSTALLING_SOFTWARE = 'INSTALLING_SOFTWARE'
    SOFTWARE_INSTALLED = 'SOFTWARE_INSTALLED'
    SOFTWARE_READY = 'SOFTWARE_READY'
