from enum import Enum


class NodeStatus(Enum):
    CHECKING_SOFTWARE_VERSION = 'CHECKING_SOFTWARE_VERSION'
    DOWNLOADING_SOFTWARE = 'DOWNLOADING_SOFTWARE'
    INSTALLING_SOFTWARE = 'INSTALLING_SOFTWARE'
    SOFTWARE_READY = 'SOFTWARE_READY'


