# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v0131beta.verrpc import verrpc_pb2 as v0131beta_dot_verrpc_dot_verrpc__pb2


class VersionerStub(object):
    """Versioner is a service that can be used to get information about the version
    and build information of the running daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/verrpc.Versioner/GetVersion',
                request_serializer=v0131beta_dot_verrpc_dot_verrpc__pb2.VersionRequest.SerializeToString,
                response_deserializer=v0131beta_dot_verrpc_dot_verrpc__pb2.Version.FromString,
                )


class VersionerServicer(object):
    """Versioner is a service that can be used to get information about the version
    and build information of the running daemon.
    """

    def GetVersion(self, request, context):
        """lncli: `version`
        GetVersion returns the current version and build information of the running
        daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VersionerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=v0131beta_dot_verrpc_dot_verrpc__pb2.VersionRequest.FromString,
                    response_serializer=v0131beta_dot_verrpc_dot_verrpc__pb2.Version.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verrpc.Versioner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Versioner(object):
    """Versioner is a service that can be used to get information about the version
    and build information of the running daemon.
    """

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verrpc.Versioner/GetVersion',
            v0131beta_dot_verrpc_dot_verrpc__pb2.VersionRequest.SerializeToString,
            v0131beta_dot_verrpc_dot_verrpc__pb2.Version.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
